var transit = {
  "TransitOutcomesBNN": {
    "Description": "Potential outcomes based on Transiting Jupiter and Transiting Saturn influencing Natal Planets according to Bhrigu Nandi Nadi (BNN) principles presented in the sources. Note: These are general potential outcomes when influence occurs; determining *if* influence occurs requires comparing current transit positions to individual natal chart positions based on rules (same rashi, aspects, trines, 3/11 houses). The keys within 'JupiterTransits' and 'SaturnTransits' refer to the *natal* planet being influenced by the transiting planet.",
    "JupiterTransits": {
      "Sun": [
        "Activation of natal sun",
        "Events related to Government",
        "Events related to Govt. Job",
        "Events related to MBA",
        "Events related to Authority",
        "Events related to Politics",
        "Events related to Name",
        "Events related to Fame",
        "Events related to promotion",
        "Issues related to government may be solved with help of somebody in authority",
        "Respect",
        "Promotion",
        "Cooperation from Higher Authorities",
        "Male Progeny Prospects"
      ],
      "Moon": [
        "Blames",
        "Change (residence, city, job)",
        "Litigation",
        "Travel to some place",
        "Mother may turn devotional",
        "Native may turn devotional",
        "Causes change in life",
        "Birth of female child",
        "Interaction with opposite sex",
        "Change of residence",
        "Mother turns devotional",
        "Birth of Female Child",
        "Changes",
        "travelling",
        "Foreign travel",
        "Contact with Females",
        "Blames",
        "ill health",
        "Cold related Problems"
      ],
      "Mercury": [
        "For students, new knowledge",
        "For students, success in exams",
        "Younger siblings gets prosperity",
        "Cooperation from knowledgeable persons",
        "Gains from land deals",
        "Professionals may have successful trainings or meetings",
        "Native may have friendship/relationship",
        "Profits in Business",
        "Educational Successes",
        "New Knowledge",
        "Landed Gains",
        "Professional Training",
        "Official Meetings",
        "Learning Occult Sciences"
      ],
      "Venus": [
        "Affluence",
        "Prosperity",
        "Money",
        "Luxury",
        "Vehicles (Car, two-wheeler)",
        "Comforts",
        "Renovation in house",
        "Celebration and buying",
        "Rise in comforts",
        "Marriage in male chart",
        "Daughter birth",
        "House purchase (Ghar is Venus)",
        "A person may work hard to get money",
        "Start working in bank",
        "Does entertainment",
        "Marriage Prospects for Male Native",
        "Affluence",
        "Assets",
        "Celebrations",
        "Construction of House",
        "purchase of luxury goods",
        "Female progeny"
      ],
      "Mars": [
        "Haste",
        "Stubbornness",
        "Keeps away from intimates",
        "Develops exercising power",
        "Blood pressure issues",
        "Construction job/work may be successful",
        "Land job/work may be successful",
        "Technical skills job/work may be successful",
        "One of the brothers will be benefitted and gets recognition, name, fame",
        "Husband will be benefitted and gets recognition, name, fame",
        "Marriage in female chart",
        "If married, promotion of husband",
        "Adamancy",
        "Impulsiveness",
        "Blood Pressure",
        "Anger",
        "Disputes",
        "Construction or Technical Activities",
        "Marriage Prospects for Female Natives and if married her Husband gets Promotion"
      ],
      "Jupiter": [
        "Very good time for native to concentrate on self development",
        "Name/Fame is activated",
        "Fortune is activated",
        "Decision to make addition in family (family planning)",
        "If childbirth during this phase it is result of good past karma",
        "Name and Fame",
        "Very Good Time",
        "Respect",
        "Male Progeny"
      ],
      "Saturn": [
        "Employment/Promotion for native",
        "Smooth period in career",
        "Could be change in job/profession",
        "If natal Mars is linked to natal Saturn, then obstructions in getting job or promotion",
        "Employment",
        "Promotion",
        "Transfer",
        "smooth going period"
      ],
      "Rahu": [
        "Native will be under illusions",
        "May lead to sickness",
        "May lead to hospitalization",
        "May lead to surgery",
        "May lead to medication",
        "Native may get disease (intensity depends on malefic impact on natal Jupiter)",
        "Problems may be related to food poisoning",
        "Problems may be related to wrong medicine",
        "Problems may be related to unknown medicine reaction",
        "Good effects of Jupiter may be obstructed",
        "Jeev is caught in maya (Circumstances due to lust, excessive desire which may later on cause problems)",
        "New beginning",
        "Operation",
        "Surgery",
        "Ill Health",
        "News of Death",
        "Fear",
        "Abortion"
      ],
      "Ketu": [
        "Gives divine knowledge",
        "Gives occult powers",
        "Being a planet of blocking nature, will block materialistic gains",
        "Obstructs a person from materialistic pursuits",
        "Materialistic results will not be good if question is regarding materialism",
        "May be positive if question is regarding law, occult, yoga, spirituality",
        "Gives choking effect",
        "Pains in joints",
        "Opposite energies",
        "Ill health",
        "Contemplation",
        "Nervous debility",
        "Ill health",
        "Divya Gnana",
        "Meeting Sadh Gurus",
        "Going on Pilgrimage"
      ]
    },
    "SaturnTransits": {
      "Sun": [
        "Stress and opposition in professional field",
        "Will get recognition and support from parental side",
        "Face troubles from higher position people (In job, govt.)",
        "Makes Sun a commoner, subject to law of karma",
        "Ill health to native",
        "Health issues/professional hazards to Father due to new people",
        "Govt. Job",
        "Financial Stress",
        "Disputes with Son or Father or Superior officers",
        "Professional Harassment",
        "trouble by government",
        "Ill Health to Father"
      ],
      "Moon": [
        "Called Sade Sati",
        "Person feels restless",
        "May wake up at midnight (2 am) and feel restless",
        "Feels like truck on head",
        "Changes in profession",
        "Transfers",
        "Blames",
        "Displeasures",
        "Expenses",
        "Cold-cough related problems",
        "If moon is weak, a wicked women may cause issues",
        "Health issues to mother",
        "Transfer",
        "Change of Job or Profession or Business",
        "Loss in Business",
        "Unnecessary Blames",
        "Expenditure",
        "Cheating",
        "Cold related problems",
        "travelling",
        "adultery",
        "sudden changes in life",
        "Mother will undergo ill health"
      ],
      "Mercury": [
        "For students, good educational success",
        "For students, delayed but with cooperation of family/friends",
        "Native may get new degree",
        "Native may get knowledge",
        "Native may get training",
        "Business success",
        "Start of business",
        "Gain of land for siblings",
        "Good for siblings",
        "May get commercial land",
        "Educational Success for Students",
        "New Knowledge and Professional Training",
        "Profits in Business and Commercial activities",
        "landed benefits",
        "purchase of lands",
        "Help or support from friends"
      ],
      "Venus": [
        "Marriage Aspects",
        "Girlfriend",
        "Assets",
        "Birth of daughter",
        "Good financial prospects",
        "1st round of Saturn (0-30 years) over Venus gives first professional income",
        "House acquisition",
        "Vehicle acquisition",
        "Prosperities",
        "Affluence in life",
        "Bound to give money or House, luxuries, job, prosperity",
        "Cannot give if free will is wasted in entertainment",
        "Marriage Prospects for Male Natives",
        "Financial Benefits from Wife",
        "Female Progeny",
        "Celebration at Home",
        "Purchase of Car",
        "House",
        "Assets",
        "Financial Stability"
      ],
      "Mars": [
        "Mental Tensions",
        "Harassment in profession",
        "Pressure from higher ups",
        "Disputes at workplace",
        "Quarrels at workplace (Due to ego and dominance)",
        "Purchase of land",
        "Opening of factory",
        "Construction related work",
        "Me with Natal Mars may support IT, Technical skills",
        "Native thinks to quit job",
        "New job is less paid",
        "Husband may suffer from ill health and laziness",
        "Mental Tensions",
        "Professional Harassment",
        "Quarrels",
        "Disputes with Superior Officers at Work Place",
        "Obstacles to Income",
        "Disputes with Husband for Female Natives",
        "Disputes with Brother"
      ],
      "Jupiter": [
        "Professional growth",
        "Status enhancement",
        "Promotion",
        "Good opportunities",
        "New avenues",
        "Life settling transit",
        "Turning point of life",
        "Gastric problems",
        "New Job",
        "Promotion",
        "Transfer",
        "Development",
        "Professional Growth",
        "Respect",
        "Friendship with Big Personalities",
        "gastric problems"
      ],
      "Saturn": [
        "Additional Work due to heavy workload",
        "Efficiency level drops",
        "Laziness surrounds native",
        "Performance slows down",
        "Nervous breakdown",
        "Change in lifestyle",
        "Health problems",
        "Gastric troubles",
        "Person may have to work double or much harder",
        "Work Tension",
        "Heavy or Additional Work",
        "troubles"
      ],
      "Rahu": [
        "Person may involve in shadowy activities",
        "Unethical work",
        "Work at foreign places",
        "Foreign travel",
        "Death in house (related event)",
        "Has to do or attend mourning ceremony",
        "Purchase of vehicles",
        "Laziness",
        "Can be good if person starts something new (initial problems - 1st year)",
        "Online business",
        "MNC work",
        "Software engineering etc.",
        "Foreign Travel",
        "Hard Work",
        "Low Salary Jobs",
        "Purchase of Vehicles",
        "Professional Disturbances",
        "Legal Problems",
        "Unethical deeds",
        "corruption",
        "death in the house"
      ],
      "Ketu": [
        "Dejections and disputes at work",
        "May involve in litigation",
        "Aimlessness",
        "May visit holy places",
        "Financial losses",
        "Quitting the job (Constant thought)",
        "Period of depression",
        "Stress",
        "Karmo ki maar (results of all bad deeds)",
        "Person should not change job unless he/she has an offer letter",
        "Unemployed",
        "Vexation with the Job",
        "Termination or Resignation",
        "Professional Disturbances",
        "No Aim or Ambition",
        "Legal Problems",
        "I T OR CBI OR ACB Rides",
        "litigation",
        "disputes",
        "Imprisonment",
        "visiting holy places"
      ]
    }
  }
};